[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
assert_program = "CrGmBj9LobsbkVHXPguToqmyZoPgAAtf1gbf5795t91W"

[programs.devnet]
assert_program = "CrGmBj9LobsbkVHXPguToqmyZoPgAAtf1gbf5795t91W"

[programs.mainnet]
assert_program = "CrGmBj9LobsbkVHXPguToqmyZoPgAAtf1gbf5795t91W"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/scawf/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

# IDL -> 5BX6t9UtKdNyHzyuXHUqUWNzWt7rNR4JiNYZjdqBpNHY